spring:
  application:
    name: loan
  datasource:
    url: jdbc:mysql://localhost:3308/sys
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  profiles:
    active: prod

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  config:
    import: "optional:configserver:http://localhost:8071/"
#  optional:configserver:http://localhost:8071/ - add optional when the file is not that important
server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"